accountapp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),
    # 클래스형 view를 넣을때는 .as_view()를 추가해야한다고함.
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    # login view
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('articleapp.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribes/', include('subscribeapp.urls')),
# 이미지를 화면에 보여주기 위한 static을 추가해준다고합니다.
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update')
]

accountapp/models.py
from django.db import models


# Create your models here.

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.form import AccountUpdateForm

from articleapp.models import Article

has_ownershop = [login_required, account_ownership_required]


# @login_required
# def hello_world(request):
#     # return HttpResponse('Hello world!!!!!!')
#     if request.method == 'POST':
#         # POST로 form 보냈을때 받아오는방법
#         temp = request.POST.get('hello_world_input')
#
#         # 받아온 데이터를 model에 저장하는방법
#         # 새로운 객체를 만들어서 거기에 넣고
#         # 마지막에 save까지 해줘야함.
#         # new_HelloWorld = HelloWorld()
#         # new_HelloWorld.text = temp
#         # new_HelloWorld.save()
#
#         # 모델 객체의 모든 정보를 가져옴
#         # hello_world_list = HelloWorld.objects.all()
#
#         # 받아온 데이터를 다시 html로 보낼때
#         # render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})
#         return HttpResponseRedirect(reverse('accountapp:hello_world'))
#     else:
#         # 모델 객체의 모든 정보를 가져옴
#         # hello_world_list = HelloWorld.objects.all()
#         return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


# class base view가 훨씬 직관적이고 편하다. django의 좋은기능? 같음.
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    # reverse 와 reverse_lazy의 차이? : reverse_lazy는 클래스에서만 사용할수 있다. 클래스안에서 reverse는 안됨. reverse는 함수형에서
    # submit성공했을때 redirect설정
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView, MultipleObjectMixin):
    # 이 두개만 있으면 됨
    model = User
    template_name = 'accountapp/detail.html'
    context_object_name = 'target_user'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(has_ownershop, 'get')
@method_decorator(has_ownershop, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/update.html'
    context_object_name = 'target_user'


@method_decorator(has_ownershop, 'get')
@method_decorator(has_ownershop, 'post')
class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'
    context_object_name = 'target_user'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content  %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUP</h4>
        </div>
            <!--        어떤앱에서:어떤라우팅으로가라-->
        <form action="{% url 'accountapp:create' %}" method="post">
<!--            장고에서 post method를 쓰려고하면 form 내부에 첫번째로 붙여야하는거-->
            {% csrf_token %}
<!--            view.py에서 AccountCreateView클래스에서 선언한 form_class가 구성해놓은 form 객체 바로 불러옴-->
<!--            {{ form }}-->
            {% bootstrap_form form%}
            <input type="submit" value="제출" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
        
    </div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
          <h4>Delete</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
        {% csrf_token %}

        <input type="submit" value="탈퇴" class="btn btn-danger rounded-pill col-6 mt-3">

    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <p>
        {{ target_user.date_joined }}
    </p>



    {% if target_user.profile %}
       <img src="{{ target_user.profile.image.url }}" alt="" style="height:12rem; width: 14rem; border-radius: 10rem; margin-bottom: 2rem; object-fit: cover;">
    <H2>
        {{ target_user.profile.nickname }}
            {% if target_user == user %}
        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
            class="material-icons"
            style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;">
            account_circle
        </a>
            {% endif %}
    </H2>
    <h5 style="margin-bottom: 3rem;">
        {{ target_user.profile.message }}
    </h5>

    {% else %}
        {% if target_user == user %}
<!--    <h2>else에있음</h2>-->
    <a href="{% url 'profileapp:create' %}">
        <H2>
        Create Profile
        </H2>
        {% else %}
        <H2> 닉네임 미설정!</H2>
    </a>
        {% endif %}

    {% endif %}


    {% if target_user == user %}
    <a href="{% url 'accountapp:update' pk=user.pk %}"
        class="material-icons"
        style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;">
        <p>
            settings
        </p>
    </a>

    <a href="{% url 'accountapp:delete' pk=user.pk %}"
        class="material-icons"
        style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;">
        <p>
            cancel
        </p>
    </a>
    {% endif %}
</div>

    <div>
        {% include 'snippets/list_pragment.html' with article_list=object_list %}
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}


{% block content %}
<div style=" border-radius: 1rem; margin: 2rem; text-align: center;">
    <H1 class="pragmatic_logo">
        Hello world List!
    </H1>

    <form action="/account/hello_world/" method="post">
        {% csrf_token %}
        <div>
            <input type="text" name="hello_world_input">
        </div>
        <input type="submit" class="btn btn-primary" value="POST">
    </form>
    {% if hello_world_list %}
        {% for hello_world in hello_world_list %}
        <H4>
            {{ hello_world.text }}
        </H4>
        {% endfor %}
    {% endif %}
</div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
<!--                {{ form }}-->
                {% bootstrap_form form %}
                <input type="submit" value="제출" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content  %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
            <!--        어떤앱에서:어떤라우팅으로가라-->
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
<!--            장고에서 post method를 쓰려고하면 form 내부에 첫번째로 붙여야하는거-->
            {% csrf_token %}
<!--            view.py에서 AccountCreateView클래스에서 선언한 form_class가 구성해놓은 form 객체 바로 불러옴-->
<!--            {{ form }}-->
            {% bootstrap_form form%}
            <input type="submit" value="제출" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
        
    </div>


{% endblock %}