accountapp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    # path('hello_world/', hello_world, name='hello_world'),
    # 클래스형 view를 넣을때는 .as_view()를 추가해야한다고함.
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
    # login view
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    # path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('list/', ArticleListView.as_view(), name='list'),
    path('', ArticleListView.as_view(), name='list'),

]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('articleapp.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accountapp.urls')),
                  path('profiles/', include('profileapp.urls')),
                  path('articles/', include('articleapp.urls')),
                  path('comments/', include('commentapp.urls')),
                  path('projects/', include('projectapp.urls')),
                  path('subscribes/', include('subscribeapp.urls')),
# 이미지를 화면에 보여주기 위한 static을 추가해준다고합니다.
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectListView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('list/', ProjectListView.as_view(), name='list'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubsciptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubsciptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}
<body>

    {% include 'header.html' %}
<Hr>
    {% block content %}
    {% endblock %}
<hr>
    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>foot11</span>
        <span>foot22</span>
        <span>foot33</span>
    </div>
    <div class="pragmatic_logo">
        <h6>Pragmatic footer</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
<!--    모바일에서도 어느정도 맞추기 위한 설계-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pragmatic</title>
<!--    BOOTSTRAP LINK   -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


<!--구글폰트-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Edu+VIC+WA+NT+Beginner&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">



    <!-- css 링크 -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

<!--    네이버폰트-->
<!--    <link href="https://hangeul.pstatic.net/hangeul_static/css/NanumNeuRisNeuRisCe.css" rel="stylesheet">-->
<!--    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-myeongjo-eco.css" rel="stylesheet">-->
<!--    <style>-->
<!--        @font-face {-->
<!--            font-family: 'NanumNeuRisNeuRisCe';-->
<!--            src: local('NanumNeuRisNeuRisCe'),-->
<!--            url("{% static 'fonts/NanumNeuRisNeuRisCe.ttf' %}") format('opentype");-->
<!--        }-->
<!--    </style>-->

<!--    구글 아이콘 가져오게하는-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

</head>

templates/header.html
<div class="pragmatic_header">
    <div class="pragmatic_logo"><h1> Pragmatic</h1></div>
    <div class="pragmatic_header_button">


        <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
            <span>Subscription</span>
        </a>


<!--        로그인/로그아웃 onoff 설정-->
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{request.path}}" class="pragmatic_header_nav">
            <span>Login</span>
        </a>

        <a href="{% url 'accountapp:create' %}" class="pragmatic_header_nav">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav">
            <span>Mypage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{request.path}}" class="pragmatic_header_nav">
            <span>Logout</span>
        </a>
        {% endif %}
    </div>
</div>